version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: maisons_edition
    ports:
      - "5432:5432"
    volumes:
      - ./serveur/init-db/init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build: ./server
    container_name: backend-server
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: maisons_edition
